# Generated by Django 3.2.6 on 2021-08-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='employers',
        ),
    ]
