# Generated by Django 3.2.6 on 2021-08-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='hr_employer',
        ),
    ]
