# Generated by Django 3.2.6 on 2021-08-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20210817_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'hr_notes',
            },
        ),
        migrations.RenameModel(
            old_name='Employer',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='hr_user',
        ),
    ]
