# Generated by Django 3.2.6 on 2021-08-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20210819_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
