# Generated by Django 3.2.6 on 2021-08-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_note_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
