# Generated by Django 3.2.6 on 2021-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_user_id_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.CharField(default='Dear Diary', max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
